name = "Innicia-Client"
author = "_gorbodoh_"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7723144677126012ecc469e5d35c79056c6448c56b6991332d1df29347decf7"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
