name = "Innicia-Client"
author = "_gorbodoh_"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b30da83b819d14e78c2bd0ffa4586a30b3f3ceb864b375d417e6fe7ebac1e846"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
